### ISSUE TITLE
Tracking: Prepare awx-operator for rsyslog sidecar container

### ISSUE THREAD

**Issue by relrod** [ansible/tower-operator#1121]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that AWX Operator is open source software provided for free and that I might not receive a timely response.

### Feature Summary

As part of the [rsyslog decoupling](https://github.com/ansible/awx/issues/13183) we need to change a few things about the deployment for awx-operator:

- [ ] We will need to change the awx-operator `Deployment` to introduce a new `awx-rsyslog` container in the pod.
- [ ] This can use the standard image that most of the other containers already use.
- [ ] I envision this functioning similarly to how we launch supervisor in the other containers, so using the web or task container as a model is probably reasonable. `roles/installer/defaults/main.yml` will need new entries, too, to make the container use `launch_awx_rsyslog.sh`.

Being able to test the outcome of this task depends on https://github.com/ansible/awx/issues/13191 being done.

**Comment by jay-steurer** [comment]
@CFSNM is working on the test coverage for this task as part of a new feature.
