### ISSUE TITLE
[Epic] Create and publish AWX operator docs 

### ISSUE THREAD

**Issue by samccann** [ansible/tower-operator#1356]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that AWX Operator is open source software provided for free and that I might not receive a timely response.

### Feature Summary

This epic is to use the current docs and readme to create and publish AWX operator documentation to Read The Docs.

- [x] [Create scaffolding to make the docs locally](https://github.com/ansible/awx-operator/issues/1359)
- [ ] [Split up the readme into multiple files ](https://github.com/ansible/awx-operator/issues/1360)
- [ ] Edit and restructure the docs folder as needed to make a coherent set of guides
- [ ] Publish docs to readthedocs docsite

**Comment by samccann** [comment]
Hmm...can't seem to assign this to myself but when y'all triage. go ahead and assign to me.

I'll be running a mini project on the #docs matrix channel on Thursdays to get community help on this effort. We'll use this issue and the subissues to coordinate work etc.
